Repository alexandrevilain/temporal-operator, pull requests merged in 2023-06, with the labels that each got.

#371 change hardcode index name for using from env vars {{ .Indices.Visibility }}
  internal/resource/persistence/template.go
Labels: bugfix

#375 Add support for Kubernetes 1.27
  .github/workflows/e2e.yaml
  README.md
  docs/api/v1beta1.md
  go.mod
  go.sum
  hack/api/config.json
  webhooks/temporalcluster_webhook.go
  webhooks/temporalcluster_webhook_test.go
  webhooks/temporalworkerprocess_webhook.go
Labels: feature

#383 Update SetupAdvancedVisibility for use custom index_patterns {{.Indic…
  internal/resource/persistence/template.go
Labels: bugfix

#393 Add support for Elasticsearch v8 (with e2e tests)
  .github/workflows/e2e.yaml
  Makefile
  api/v1beta1/temporalcluster_defaults.go
  api/v1beta1/temporalcluster_types.go
  config/crd/bases/temporal.io_temporalclusters.yaml
  examples/cluster-postgres-es/03-temporal-cluster.yaml
  go.mod
  internal/resource/persistence/schema_scripts_configmap_builder.go
  internal/resource/persistence/template.go
  tests/e2e/main_test.go
  tests/e2e/persistence_test.go
  tests/e2e/testdata/elasticsearch/elasticsearch.yaml
  tests/e2e/utils_test.go
Labels: improvement

#396 Add support for resources, replicas and overrides for services, ui and adminstools deployments
  Makefile
  api/v1beta1/temporalcluster_defaults.go
  api/v1beta1/temporalcluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/temporal.io_temporalclusters.yaml
  docs/api/v1beta1.md
  internal/resource/admintools/deployment_builder.go
  internal/resource/base/deployment_builder.go
  internal/resource/ui/deployment_builder.go
Labels: improvement

#397 Bump kubernetes dependencies to v0.27.3
  go.mod
  go.sum
Labels: dependencies

#401 Add example for temporal-ui
  docs/features/temporal-ui.md
Labels: documentation
