Repository alexandrevilain/temporal-operator, pull requests merged in 2023-07, with the labels that each got.

#420 Increase default resources limits & requests for controller
  bundle/manifests/temporal-operator.clusterserviceversion.yaml
Labels: bugfix

#416 Add option to skip create database or keyspace
  api/v1beta1/temporalcluster_types.go
  config/crd/bases/temporal.io_temporalclusters.yaml
  docs/api/v1beta1.md
  internal/resource/persistence/schema_scripts_configmap_builder.go
  internal/resource/persistence/template.go
Labels: improvement

#417 Update cert-manager.md
  mkdocs.yml
Labels: documentation

#421 Add support for temporal v1.21.x and support for Advanced visibility on SQL DBs
  api/v1beta1/temporalcluster_defaults.go
  api/v1beta1/temporalcluster_types.go
  config/crd/bases/temporal.io_temporalclusters.yaml
  controllers/reconcile_persistence.go
  internal/resource/base/configmap_builder.go
  internal/resource/persistence/schema_scripts_configmap_builder.go
  internal/resource/persistence/template.go
  pkg/version/version.go
  tests/e2e/persistence_test.go
  webhooks/temporalcluster_webhook.go
  webhooks/temporalcluster_webhook_test.go
Labels: feature

#426 Add ability to add extra labels on ServiceMonitors
  api/v1beta1/temporalcluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/temporal.io_temporalclusters.yaml
  docs/api/v1beta1.md
  examples/cluster-postgres/02-temporal-cluster.yaml
  internal/resource/prometheus/servicemonitor_builder.go
  tests/e2e/main_test.go
  tests/e2e/persistence_test.go
  tests/e2e/testdata/elasticsearch/elasticsearch.yaml
  tests/e2e/testdata/postgres/deployment.yaml
  tests/e2e/util/kubernetes/forward.go
  tests/e2e/utils_test.go
Labels: improvement
