Repository alexandrevilain/temporal-operator, pull requests merged in 2023-09, with the labels that each got.

#491 chore(deps): bump controller-tools to v0.2.2 to fix discovery caching issue
  go.mod
  go.sum
  tests/e2e/namespace_test.go
Labels: bugfix

#492 chore(lint): enable more linters
  .golangci.yaml
  Makefile
  controllers/temporalcluster_controller.go
  controllers/temporalnamespace_controller.go
  controllers/temporalworkerprocess_controller.go
  internal/resource/config/configmap_builder.go
  internal/resource/persistence/schema_scripts_configmap_builder.go
  pkg/temporal/log/sdk_adapter.go
  tests/e2e/main_test.go
  tests/e2e/utils_test.go
  webhooks/temporalcluster_webhook.go
  webhooks/temporalworkerprocess_webhook.go
Labels: improvement

#497 Add docs about overriding UI deployment
  docs/features/overrides.md
  docs/features/temporal-ui.md
Labels: documentation

#493 chore(test): improve pkg/status coverage
  controllers/temporalcluster_controller.go
  pkg/status/status.go
  pkg/status/status_test.go
Labels: improvement

#490 chore(tooling): Add script to publish release to OperatorHub
  Makefile
  bundle/manifests/temporal-operator.clusterserviceversion.yaml
  config/manifests/bases/temporal-operator.clusterserviceversion.yaml
  hack/operatorhub.sh
Labels: improvement

#514 fix(persistence): remove omitempty on datastore skipCreate to prevent useless mutatingwebook patches
  api/v1beta1/temporalcluster_types.go
Labels: bugfix
